/**
 * Mock Data Service for AE-02 Autonomous Research Agent.
 */

import type {
  ActivityEvent,
  AuditLogEntry,
  EvaluationResult,
  GovernancePermission,
  HumanApprovalRequest,
  RAGResult,
  ResearchHistoryItem,
  ResearchPlan,
  ResearchSessionStatus,
  SelfImprovementIteration,
  SandboxExecution,
  SourceItem,
  StructuredReport,
  WorkflowNode,
} from '@/types'

export const MOCK_SESSION_STATUS: ResearchSessionStatus = {
  session_id: 'sess-pothole-002',
  status: 'running',
  question: 'Is AI-based pothole detection practical for Indian roads?',
  current_iteration: 2,
  max_iterations: 3,
  confidence_threshold: 80,
  current_step: 'step-eval-05',
  progress_percentage: 75,
  created_at: new Date(Date.now() - 450000).toISOString(),
  updated_at: new Date(Date.now() - 12000).toISOString(),
  estimated_completion: '1 min remaining',
}

export const MOCK_WORKFLOW_NODES: WorkflowNode[] = [
  { id: 'START', label: 'START', description: 'User research prompt initialized', status: 'completed' },
  { id: 'PLANNER', label: 'PLANNER', description: 'Decompose prompt into autonomous plan', status: 'completed', metrics: '7 steps planned' },
  { id: 'RESEARCH', label: 'RESEARCH', description: 'Multi-query web retrieval & scraping', status: 'completed', metrics: '14 queries executed' },
  { id: 'BROWSER_SEARCH', label: 'BROWSER / SEARCH', description: 'Live web scraping & site rendering', status: 'completed', metrics: '12 sources verified' },
  { id: 'RAG', label: 'RAG DB', description: 'Vector similarity search in knowledge base', status: 'completed', metrics: '8 chunks retrieved (Sim: 0.91)' },
  { id: 'ANALYZER', label: 'ANALYZER', description: 'Synthesize evidence & cross-validate', status: 'completed', metrics: 'Cross-checked 5 datasets' },
  { id: 'EVALUATOR', label: 'EVALUATOR', description: 'Score research confidence & gaps', status: 'running', metrics: 'Iteration 2 scoring...' },
  { id: 'CONFIDENCE_CHECK', label: 'CONFIDENCE CHECK', description: 'Evaluate threshold (Current: 86.5% vs 80%)', status: 'pending' },
  { id: 'IMPROVE_STRATEGY', label: 'IMPROVE STRATEGY', description: 'Self-adjust prompt focus if < 80%', status: 'skipped', active_iteration: 1 },
  { id: 'REPORT', label: 'FINAL REPORT', description: 'Generate comprehensive findings report', status: 'pending' },
]

export const MOCK_PLAN: ResearchPlan = {
  plan_id: 'plan-pothole-101',
  session_id: 'sess-pothole-002',
  question: 'Is AI-based pothole detection practical for Indian roads?',
  objective: 'Evaluate hardware feasibility, Computer Vision model accuracy, cost per km, and Indian road conditions (monsoon damage, dust, traffic patterns).',
  iteration: 2,
  rationale: 'Iteration 1 achieved 61% confidence due to sparse real-world Indian road telemetry data. Iteration 2 focuses specifically on deployment cost analysis and dashcam vs smartphone sensor fusion.',
  created_at: new Date().toISOString(),
  steps: [
    {
      step_id: 'step-1',
      order: 1,
      title: 'Analyze Problem & Indian Road Specs',
      tool: 'planner',
      description: 'Decompose pothole detection parameters (YOLOv8, Edge-AI, CCTV, Mobile dashcams).',
      dependencies: [],
      success_criteria: 'Key parameters defined.',
      status: 'completed',
    },
    {
      step_id: 'step-2',
      order: 2,
      title: 'Live Web & Academic Search',
      tool: 'browser',
      description: 'Scrape recent 2024–2026 research papers on road surface monitoring in developing nations.',
      dependencies: ['step-1'],
      success_criteria: '≥ 10 peer-reviewed sources.',
      status: 'completed',
    },
    {
      step_id: 'step-3',
      order: 3,
      title: 'RAG Knowledge Base Retrieval',
      tool: 'rag',
      description: 'Retrieve internal vector database embeddings on Indian NHAI road standards.',
      dependencies: ['step-2'],
      success_criteria: 'Vector similarity ≥ 0.85.',
      status: 'completed',
    },
    {
      step_id: 'step-4',
      order: 4,
      title: 'Sandbox Simulation Experiment',
      tool: 'sandbox',
      description: 'Execute Python simulation benchmarking YOLOv8 Nano FPS on Raspberry Pi 4 vs Jetson Nano.',
      dependencies: ['step-3'],
      success_criteria: 'Benchmark metrics generated.',
      status: 'completed',
    },
    {
      step_id: 'step-5',
      order: 5,
      title: 'Evidence Analysis & Synthesis',
      tool: 'analyzer',
      description: 'Cross-reference lab accuracy against real-world road dust and rain occlusion factors.',
      dependencies: ['step-4'],
      success_criteria: 'Synthesis matrix ready.',
      status: 'completed',
    },
    {
      step_id: 'step-6',
      order: 6,
      title: 'Evaluate Confidence Score',
      tool: 'evaluation',
      description: 'Calculate 5-dimension confidence breakdown and verify if overall score ≥ 80%.',
      dependencies: ['step-5'],
      success_criteria: 'Confidence score calculated.',
      status: 'running',
    },
    {
      step_id: 'step-7',
      order: 7,
      title: 'Generate Final Research Report',
      tool: 'planner',
      description: 'Compile structured report with findings, limitations, and recommendations.',
      dependencies: ['step-6'],
      success_criteria: 'Report published.',
      status: 'pending',
    },
  ],
}

export const MOCK_SOURCES: SourceItem[] = [
  {
    id: 'src-1',
    title: 'Computer Vision for Automated Road Hazard Detection in Indian Urban Traffic',
    url: 'https://doi.org/10.1016/j.trc.2024.10421',
    domain: 'sciencedirect.com',
    source_type: 'Research Paper',
    relevance_score: 96,
    evidence_score: 92,
    verification_status: 'Verified',
    accessed_at: '2026-08-07T10:32:12Z',
    excerpt: 'Evaluated YOLOv8-nano models deployed on public transit buses across Mumbai and Bengaluru. Achieved 89.4% mAP under daylight conditions, dropping to 74.2% during severe monsoon rainfall.',
    authors: ['Dr. A. Sharma', 'R. Kulkarni et al.'],
    publication_date: '2024-11-15',
  },
  {
    id: 'src-2',
    title: 'NHAI Guidelines for Intelligent Transport Systems & Pothole Repair Protocols',
    url: 'https://nhai.gov.in/policies/its-pothole-guidelines-2025.pdf',
    domain: 'nhai.gov.in',
    source_type: 'Government',
    relevance_score: 94,
    evidence_score: 95,
    verification_status: 'Verified',
    accessed_at: '2026-08-07T10:32:15Z',
    excerpt: 'Mandates automated road quality audits every quarter for national highway concessionaires using LiDAR or optical AI inspection vehicles.',
    authors: ['Ministry of Road Transport & Highways'],
    publication_date: '2025-02-10',
  },
  {
    id: 'src-3',
    title: 'Edge AI Deployment Cost Benchmarks: Jetson Orin Nano vs Mobile Apps',
    url: 'https://arxiv.org/abs/2501.09812',
    domain: 'arxiv.org',
    source_type: 'Research Paper',
    relevance_score: 88,
    evidence_score: 90,
    verification_status: 'Verified',
    accessed_at: '2026-08-07T10:32:18Z',
    excerpt: 'Smartphones mounted on auto-rickshaws provide 1/10th the hardware cost of dedicated LiDAR rigs while achieving 84% detection accuracy for severe potholes (>5cm depth).',
    authors: ['V. Patel', 'M. Iyer'],
    publication_date: '2025-01-20',
  },
  {
    id: 'src-4',
    title: 'Road Infrastructure & Pothole Accidents Statistics India 2024',
    url: 'https://morth.nic.in/reports/road-accidents-india-2024.html',
    domain: 'morth.nic.in',
    source_type: 'Government',
    relevance_score: 91,
    evidence_score: 94,
    verification_status: 'Verified',
    accessed_at: '2026-08-07T10:32:22Z',
    excerpt: 'Pothole-related road fatalities accounted for 4,400+ casualties annually, emphasizing urgent need for proactive AI repair dispatching.',
    authors: ['MoRTH Research Wing'],
    publication_date: '2025-03-01',
  },
  {
    id: 'src-5',
    title: 'Real-time OpenCV Pothole Detection on Android Devices',
    url: 'https://github.com/road-safety-ai/pothole-cv-india',
    domain: 'github.com',
    source_type: 'Documentation',
    relevance_score: 82,
    evidence_score: 85,
    verification_status: 'Verified',
    accessed_at: '2026-08-07T10:32:25Z',
    excerpt: 'Open-source TensorFlow Lite pipeline optimized for Qualcomm Snapdragon mid-range processors operating at 30 FPS.',
    authors: ['OpenRoads Tech Team'],
    publication_date: '2025-05-14',
  },
  {
    id: 'src-6',
    title: 'Commercial Fleet Analytics: Municipal Pothole Tracking Case Study',
    url: 'https://techinroads.org/case-studies/mumbai-muncipal-ai',
    domain: 'techinroads.org',
    source_type: 'Report',
    relevance_score: 79,
    evidence_score: 78,
    verification_status: 'Unverified',
    accessed_at: '2026-08-07T10:32:30Z',
    excerpt: 'Pilot testing in Brihanmumbai Municipal Corporation reduced repair lag from 14 days to 48 hours.',
    authors: ['Urban Mobility Forum'],
    publication_date: '2025-04-02',
  },
]

export const MOCK_RAG_RESULT: RAGResult = {
  documents_retrieved: 5,
  chunks_retrieved: 12,
  retrieval_time_ms: 184,
  top_chunks: [
    {
      chunk_id: 'rag-chk-001',
      document_name: 'Road Safety Research & Indian Highway Standards.pdf',
      document_type: 'PDF / Policy Manual',
      similarity_score: 0.91,
      content: 'AI-based road surface detection on Indian highways must account for high vibration levels, unpaved shoulders, and ambient dust occlusion. Smartphone accelerometer fusion with optical camera streams improves depth estimation by 28%.',
      metadata: { page: 14, author: 'NHAI Technical Committee' },
    },
    {
      chunk_id: 'rag-chk-002',
      document_name: 'Edge-AI Hardware Cost Analysis 2025.docx',
      document_type: 'Technical Report',
      similarity_score: 0.88,
      content: 'Hardware unit economics: Deploying Raspberry Pi 4 with Coral TPU costs $110 per vehicle, vs $450 for Jetson Orin Nano. Smartphone-based passive crowd-sourcing costs $0 capital expenditure if integrated into delivery rider apps.',
      metadata: { section: 'Hardware Feasibility' },
    },
    {
      chunk_id: 'rag-chk-003',
      document_name: 'Computer Vision Model Comparison for Road Hazards.txt',
      document_type: 'Research Note',
      similarity_score: 0.85,
      content: 'YOLOv8-nano provides the optimal trade-off for real-time edge processing on low-power devices, sustaining 32 FPS at 640x640 resolution with 88.6% mAP@0.5 on Indian asphalt datasets.',
      metadata: { topic: 'Model Benchmarking' },
    },
  ],
}

export const MOCK_EVALUATION_RESULT: EvaluationResult = {
  evaluation_id: 'eval-res-002',
  session_id: 'sess-pothole-002',
  iteration: 2,
  overall_confidence: 86.5,
  breakdown: {
    source_quality: 91.0,
    evidence_coverage: 88.5,
    cross_source_consistency: 85.0,
    relevance: 92.0,
    validation: 76.0,
  },
  strengths: [
    'Multiple authoritative government (MoRTH/NHAI) and peer-reviewed research papers evaluated',
    'Strong evidence coverage including model benchmarks (YOLOv8) and hardware unit economics',
    'Cross-source consistency confirmed between academic studies and field pilots in Mumbai/Bengaluru',
    'Hardware deployment costs verified for low-cost crowd-sourced vs dedicated inspection vehicles',
  ],
  weaknesses: [
    'Limited long-term hardware durability data in extreme Indian monsoon conditions (>90 days continuous exposure)',
    'Nighttime detection accuracy drops by 15-20% without infrared or high-lumen auxiliary lighting',
  ],
  recommendation: 'Perform additional edge-hardware thermals validation in sandbox simulation, but evidence is sufficient to generate final comprehensive research report.',
  decision: 'REPORT',
  evaluated_at: new Date(Date.now() - 10000).toISOString(),
}

export const MOCK_SELF_IMPROVEMENT_ITERATIONS: SelfImprovementIteration[] = [
  {
    iteration: 1,
    confidence: 61.0,
    problems_detected: [
      'Insufficient real-world Indian road telemetry data in general web search',
      'Missing cost breakdown for municipal deployment in tier-2/3 cities',
      'Conflicting claims regarding optical camera accuracy vs LiDAR',
    ],
    action_taken: 'Re-planned research strategy: Target specific Indian Ministry publications (MoRTH, NHAI) and retrieve edge-AI hardware cost papers.',
    previous_strategy: 'Broad Google search on "Pothole detection AI"',
    strategy_change: 'Filter by domain (.gov.in, IEEE, Elsevier) & add RAG vector search over internal transport database',
    new_strategy: 'Multi-query domain-scoped search + RAG retrieval + Python hardware sandbox simulation',
    result_summary: 'Confidence boosted from 61.0% to 86.5% (+25.5% improvement).',
    status: 'Improved',
  },
  {
    iteration: 2,
    confidence: 86.5,
    problems_detected: [
      'Minor gap in nighttime illumination requirements',
    ],
    action_taken: 'Threshold (80%) exceeded. Concluded research loop and proceeded to report generation.',
    previous_strategy: 'Multi-query domain-scoped search + RAG retrieval + Python hardware sandbox simulation',
    strategy_change: 'Finalize report synthesis with explicit limitations section noted',
    new_strategy: 'Generate final structured report',
    result_summary: 'Confidence 86.5% ≥ 80.0% threshold requirement. Decision: REPORT.',
    status: 'Threshold Reached',
  },
]

export const MOCK_GOVERNANCE_PERMISSIONS: GovernancePermission[] = [
  { action: 'web_search', label: 'Web Search', status: 'ALLOWED', description: 'Permitted domain-restricted search via SerpAPI/DuckDuckGo.' },
  { action: 'browser_automation', label: 'Browser', status: 'ALLOWED', description: 'Headless Playwright scraper for public HTML rendering.' },
  { action: 'rag_retrieval', label: 'RAG DB', status: 'ALLOWED', description: 'Internal ChromaDB vector store embeddings lookup.' },
  { action: 'sandbox_execution', label: 'Sandbox', status: 'ALLOWED', description: 'Isolated Docker container execution for Python benchmarks.' },
  { action: 'file_access', label: 'File Access', status: 'BLOCKED', description: 'Access to host system files outside sandbox container blocked.' },
  { action: 'system_commands', label: 'System Commands', status: 'BLOCKED', description: 'Execution of arbitrary OS shell commands strictly blocked.' },
  { action: 'external_action', label: 'External Action', status: 'HUMAN APPROVAL', description: 'Sending emails, API modifications, or API payments requires human sign-off.' },
]

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  { log_id: 'audit-001', session_id: 'sess-pothole-002', step_id: 'step-2', action_type: 'web_search', action_params: { query: 'YOLOv8 Indian pothole detection' }, verdict: 'allow', matched_policies: ['Policy-01-WebSearchDomainWhitelist'], reason: 'Target domain listed in allowed educational/research whitelist.', timestamp: new Date(Date.now() - 300000).toISOString() },
  { log_id: 'audit-002', session_id: 'sess-pothole-002', step_id: 'step-3', action_type: 'rag_retrieval', action_params: { top_k: 5 }, verdict: 'allow', matched_policies: ['Policy-04-VectorDBReadOnly'], reason: 'Read-only semantic query against internal knowledge base.', timestamp: new Date(Date.now() - 240000).toISOString() },
  { log_id: 'audit-003', session_id: 'sess-pothole-002', step_id: 'step-4', action_type: 'sandbox_execution', action_params: { timeout: 10, script: 'python_benchmark.py' }, verdict: 'allow', matched_policies: ['Policy-08-SandboxIsolationPolicy'], reason: 'Sandbox environment isolated with network restriction.', timestamp: new Date(Date.now() - 180000).toISOString() },
  { log_id: 'audit-004', session_id: 'sess-pothole-002', step_id: 'step-4', action_type: 'system_commands', action_params: { cmd: 'rm -rf /' }, verdict: 'block', matched_policies: ['Policy-12-HostSecurityGuard'], reason: 'Destructive OS shell command blocked automatically.', timestamp: new Date(Date.now() - 170000).toISOString() },
  { log_id: 'audit-005', session_id: 'sess-pothole-002', step_id: 'step-5', action_type: 'external_action', action_params: { action: 'deploy_remote_agent' }, verdict: 'warn', matched_policies: ['Policy-15-HumanInTheLoopTrigger'], reason: 'Remote action flagged for human operator approval.', timestamp: new Date(Date.now() - 120000).toISOString() },
]

export const MOCK_HUMAN_APPROVAL_REQUEST: HumanApprovalRequest = {
  request_id: 'hitl-req-99',
  session_id: 'sess-pothole-002',
  action: 'Execute high-compute Python experiment in sandbox',
  reason: 'Validate YOLOv8 hardware latency simulation across 10,000 synthetic image samples.',
  details: {
    container_image: 'python:3.11-slim',
    memory_limit: '512 MB',
    estimated_duration: '4.5 seconds',
  },
  requested_at: new Date(Date.now() - 45000).toISOString(),
  status: 'pending',
}

export const MOCK_SANDBOX_EXECUTION: SandboxExecution = {
  execution_id: 'sb-exec-204',
  session_id: 'sess-pothole-002',
  task_name: 'Python YOLOv8 Nano FPS & Hardware Latency Benchmark',
  status: 'Running',
  execution_time_seconds: 1.42,
  memory_mb: 128,
  cpu_percent: 18.4,
  network_status: 'Restricted',
  command: 'python -m benchmark --model yolov8n.onnx --target raspberry_pi4',
  logs: [
    '10:32:15.102 [INFO] Initializing isolated PyTorch/ONNX runtime container...',
    '10:32:15.340 [INFO] Loading YOLOv8-nano weights (3.2 MB)...',
    '10:32:15.520 [INFO] Running batch inference across 500 test frames (Indian asphalt dataset)...',
    '10:32:16.010 [INFO] Frame processing complete: Avg Latency = 28.4ms (35.2 FPS)',
    '10:32:16.140 [SUCCESS] Memory peak: 124.8 MB. Zero memory leaks detected.',
    '10:32:16.200 [SUCCESS] Experiment evaluation completed successfully.',
  ],
}

export const MOCK_REPORT: StructuredReport = {
  report_id: 'rep-pothole-2026',
  session_id: 'sess-pothole-002',
  question: 'Is AI-based pothole detection practical for Indian roads?',
  overall_confidence: 86.5,
  total_iterations: 2,
  generated_at: new Date().toISOString(),
  executive_summary: `AI-based pothole detection is highly practical and economically viable for Indian roads when deployed via passive edge-AI crowd-sourcing (smartphones mounted on delivery fleets or public transit buses) rather than expensive dedicated LiDAR survey vehicles. Current YOLOv8-nano Computer Vision models sustain 35+ FPS on $100 edge devices with 89.4% mean Average Precision (mAP). However, operational success hinges on sensor fusion with accelerometers and robust weather-filtering algorithms during monsoon periods.`,
  methodology: `Our autonomous research agent executed a 2-iteration self-evolving research strategy. It scraped 14 peer-reviewed and government sources (MoRTH, NHAI, IEEE, Elsevier), performed semantic retrieval over vector database manuals, executed a Python benchmark simulation in an isolated Docker sandbox, and verified findings across 5 evaluation dimensions.`,
  key_findings: [
    'Hardware Unit Economics: Passive smartphone mount deployment costs < ₹10,000 ($120 USD) per vehicle, achieving 84% accuracy for actionable road repair dispatches.',
    'Model Optimization: YOLOv8-nano achieves 35 FPS on Raspberry Pi 4 + Coral TPU hardware, sufficient for city driving speeds up to 50 km/h.',
    'Municipal Cost Savings: Municipalities (e.g., BMC Mumbai pilot) reduced road repair lag from 14 days to under 48 hours using automated AI dispatching.',
    'Monsoon Occlusion Gap: Rain and water accumulation in road depressions reduce optical accuracy by 15.2%, requiring accelerometer sensor fusion.',
  ],
  evidence: `Field data from Mumbai public bus telemetry (2024–2025) demonstrates 89.4% daylight mAP. Sandbox ONNX benchmarks confirmed 28.4ms latency per frame on low-power ARM architectures. NHAI guidelines issued in Feb 2025 formally authorize optical AI audits for national highway concessionaires.`,
  sections: [
    {
      order: 1,
      title: '1. Introduction & Problem Statement',
      content: 'Potholes cause over 4,400 road casualties annually in India according to MoRTH official statistics. Traditional manual inspections are slow, subjective, and sporadic. Automated AI detection offers continuous real-time mapping.',
      citations: [
        { title: 'MoRTH Road Accidents India 2024', url: 'https://morth.nic.in/reports', source_domain: 'morth.nic.in', accessed_at: '2026-08-07', excerpt: 'Pothole fatalities stats', relevance_score: 0.94 },
      ],
    },
    {
      order: 2,
      title: '2. Computer Vision Architecture Benchmarks',
      content: 'Benchmarking YOLOv8-nano against MobileNetV3 and ResNet-18 showed YOLOv8-nano achieves the best balance of speed (35.2 FPS) and lightweight model weight (3.2 MB), fitting effortlessly on edge devices.',
      citations: [
        { title: 'Computer Vision for Automated Road Hazard Detection', url: 'https://doi.org/10.1016/j.trc.2024.10421', source_domain: 'sciencedirect.com', accessed_at: '2026-08-07', excerpt: 'YOLOv8 evaluation on Indian asphalt', relevance_score: 0.96 },
      ],
    },
    {
      order: 3,
      title: '3. Economic Feasibility & ROI',
      content: 'Equipping 1,000 public transit buses with smartphone AI vision apps creates a daily scanning grid over 85% of city arterial roads without dedicated inspection driver salaries.',
      citations: [
        { title: 'Edge AI Deployment Cost Benchmarks', url: 'https://arxiv.org/abs/2501.09812', source_domain: 'arxiv.org', accessed_at: '2026-08-07', excerpt: 'Cost comparisons', relevance_score: 0.88 },
      ],
    },
  ],
  sources: MOCK_SOURCES,
  citations: MOCK_SOURCES.map((s) => ({
    title: s.title,
    url: s.url,
    source_domain: s.domain,
    accessed_at: s.accessed_at,
    excerpt: s.excerpt,
    relevance_score: s.relevance_score / 100,
  })),
  limitations: [
    'Nighttime detection without high-lumen headlights requires additional infrared imaging sensors.',
    'Deep water logging during peak monsoon hides subsurface pothole boundaries.',
  ],
  recommendations: [
    'Adopt smartphone-based crowd-sourcing on municipal bus fleets for immediate high-density coverage.',
    'Implement dual-modal sensor fusion (camera + smartphone accelerometer) to eliminate false positives.',
    'Integrate AI detection outputs directly into municipal GIS dispatch systems for automated contractor ticketing.',
  ],
}

export const MOCK_ACTIVITY_EVENTS: ActivityEvent[] = [
  { id: 'evt-1', session_id: 'sess-pothole-002', timestamp: '10:32:01', level: 'INFO', message: 'Research session initialized. Goal: Pothole detection feasibility in India.', node: 'START' },
  { id: 'evt-2', session_id: 'sess-pothole-002', timestamp: '10:32:02', level: 'RUNNING', message: 'Planner agent decomposing prompt into 7 sequential steps.', node: 'PLANNER' },
  { id: 'evt-3', session_id: 'sess-pothole-002', timestamp: '10:32:05', level: 'SUCCESS', message: 'Autonomous research plan created successfully.', node: 'PLANNER' },
  { id: 'evt-4', session_id: 'sess-pothole-002', timestamp: '10:32:08', level: 'RUNNING', message: 'Executing domain-restricted web search across MoRTH, NHAI, arXiv...', node: 'RESEARCH' },
  { id: 'evt-5', session_id: 'sess-pothole-002', timestamp: '10:32:12', level: 'SUCCESS', message: 'Retrieved and scraped 12 high-relevance web sources.', node: 'BROWSER_SEARCH' },
  { id: 'evt-6', session_id: 'sess-pothole-002', timestamp: '10:32:16', level: 'SUCCESS', message: 'RAG vector lookup completed: 8 top matches retrieved (Similarity: 0.91).', node: 'RAG' },
  { id: 'evt-7', session_id: 'sess-pothole-002', timestamp: '10:32:19', level: 'RUNNING', message: 'Executing Python YOLOv8 benchmark script in isolated Docker sandbox.', node: 'RESEARCH' },
  { id: 'evt-8', session_id: 'sess-pothole-002', timestamp: '10:32:22', level: 'SUCCESS', message: 'Sandbox execution complete: 35.2 FPS benchmarked. 0 security violations.', node: 'RESEARCH' },
  { id: 'evt-9', session_id: 'sess-pothole-002', timestamp: '10:32:25', level: 'WARNING', message: 'Iteration 1 confidence was 61.0% (< 80.0% threshold). Self-improving strategy...', node: 'IMPROVE_STRATEGY' },
  { id: 'evt-10', session_id: 'sess-pothole-002', timestamp: '10:32:28', level: 'SUCCESS', message: 'Iteration 2 confidence calculated: 86.5% (≥ 80.0% threshold satisfied).', node: 'EVALUATOR' },
]

export const MOCK_RESEARCH_HISTORY: ResearchHistoryItem[] = [
  {
    session_id: 'sess-pothole-002',
    question: 'Is AI-based pothole detection practical for Indian roads?',
    date: '2026-08-07 10:32',
    status: 'running',
    iterations: 2,
    sources_count: 12,
    overall_confidence: 86.5,
    tags: ['Computer Vision', 'Road Safety', 'Edge AI'],
  },
  {
    session_id: 'sess-quantum-001',
    question: 'What are the latest breakthroughs in quantum error correction surface codes?',
    date: '2026-08-06 18:15',
    status: 'completed',
    iterations: 1,
    sources_count: 15,
    overall_confidence: 91.2,
    tags: ['Quantum Computing', 'Physics'],
  },
  {
    session_id: 'sess-crispr-003',
    question: 'How does CRISPR-Cas9 compare to base editing techniques in clinical accuracy?',
    date: '2026-08-05 14:20',
    status: 'completed',
    iterations: 2,
    sources_count: 18,
    overall_confidence: 88.4,
    tags: ['Biotech', 'Genomics'],
  },
  {
    session_id: 'sess-llm-004',
    question: 'What are the economic impacts of large language models on knowledge work?',
    date: '2026-08-04 11:05',
    status: 'completed',
    iterations: 3,
    sources_count: 22,
    overall_confidence: 84.0,
    tags: ['AI Economics', 'Labor Market'],
  },
]
