"""
Planner Module Schemas

Pydantic models for research plans and task steps.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.schemas.common import StepStatus, ToolType


class TaskStep(BaseModel):
    """A single executable step in a research plan."""

    step_id: str
    order: int = Field(ge=1, description="Execution order within the plan.")
    title: str = Field(..., description="Short title for this step.")
    description: str = Field(..., description="Detailed description of what this step does.")
    tool: ToolType = Field(..., description="Which tool will execute this step.")
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Tool-specific parameters (e.g., search query, code snippet).",
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="step_ids that must complete before this step runs.",
    )
    success_criteria: str = Field(
        default="",
        description="What constitutes a successful completion of this step.",
    )
    status: StepStatus = StepStatus.PENDING
    result: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None


class ResearchPlan(BaseModel):
    """A complete, structured research plan generated by the Planner."""

    plan_id: str
    session_id: str
    question: str
    objective: str = Field(
        ..., description="High-level statement of what the plan aims to achieve."
    )
    steps: List[TaskStep] = Field(..., description="Ordered list of task steps.")
    iteration: int = Field(
        default=1, description="Which iteration this plan belongs to (1 = first)."
    )
    rationale: str = Field(
        default="",
        description="Explanation of why the planner chose this strategy.",
    )
    estimated_duration_minutes: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    adapted_from_plan_id: Optional[str] = Field(
        default=None,
        description="If this plan was adapted from a previous one, the original plan_id.",
    )

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == StepStatus.COMPLETED)
