"""
Research Module Schemas

Pydantic models for research session requests, responses, data objects,
search, document loading, chunking, embeddings, retrieval, citations,
source verification, and contradiction detection.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.schemas.common import SessionStatus


# ---------------------------------------------------------------------------
# Core Research Models
# ---------------------------------------------------------------------------
class ResearchRequest(BaseModel):
    """Request body to start a new research session."""

    question: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="The research question or topic to investigate.",
        examples=["What are the latest advances in quantum computing error correction?"],
    )
    max_iterations: int | None = Field(
        default=None,
        ge=1,
        le=10,
        description="Override for maximum research iterations (defaults to settings).",
    )
    confidence_threshold: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Stop research when this confidence score is reached.",
    )
    enable_sandbox: bool = Field(
        default=True,
        description="Whether to allow the agent to run code experiments.",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Optional tags for categorizing this research session.",
    )


class ResearchSessionStatus(BaseModel):
    """Current status of a research session."""

    session_id: str
    status: SessionStatus
    question: str
    current_iteration: int = 0
    max_iterations: int
    confidence_threshold: float = Field(default=0.75, ge=0.0, le=1.0)
    overall_confidence: float = Field(default=0.0, ge=0.0, le=100.0, description="Evaluator confidence score as a percentage (0–100).")
    current_step: str | None = None
    progress_percentage: float = Field(default=0.0, ge=0.0, le=100.0)
    created_at: datetime
    updated_at: datetime
    estimated_completion: datetime | None = None


# ---------------------------------------------------------------------------
# Search Schemas
# ---------------------------------------------------------------------------
class SearchRequest(BaseModel):
    """Request schema for web search API."""

    query: str = Field(..., min_length=2, description="Search query string.")
    max_results: int = Field(default=5, ge=1, le=20, description="Max search results.")
    search_depth: str = Field(default="basic", description="basic or advanced search depth.")
    include_domains: list[str] | None = Field(default=None, description="Restrict domains.")
    exclude_domains: list[str] | None = Field(default=None, description="Exclude domains.")


class SearchResult(BaseModel):
    """A single search result object."""

    title: str
    url: str
    content: str
    relevance_score: float = Field(default=0.8, ge=0.0, le=1.0)
    source_domain: str | None = None
    published_date: str | None = None


class SearchResponse(BaseModel):
    """Response schema for search API."""

    query: str
    results: list[SearchResult] = Field(default_factory=list)
    total_results: int = 0
    provider_used: str = "tavily"


# ---------------------------------------------------------------------------
# Document & Chunking Schemas
# ---------------------------------------------------------------------------
class Document(BaseModel):
    """Extracted document model."""

    document_id: str
    title: str
    content: str
    file_type: str = Field(..., description="pdf, docx, txt, md, csv, html")
    source_path_or_url: str | None = None
    page_count: int | None = 1
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Chunk(BaseModel):
    """Chunk model generated by recursive chunker."""

    chunk_id: str
    document_id: str
    content: str
    page_number: int | None = 1
    start_char: int = 0
    end_char: int = 0
    source: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class IngestRequest(BaseModel):
    """Request schema for document ingestion API."""

    text: str | None = Field(default=None, description="Raw text content to ingest.")
    url: str | None = Field(default=None, description="Web URL to scrape & ingest.")
    file_name: str | None = Field(default="uploaded_document.txt", description="Document title.")
    file_type: str = Field(default="txt", description="pdf, docx, txt, md, csv, html")
    metadata: dict[str, Any] = Field(default_factory=dict)


class IngestResponse(BaseModel):
    """Response schema for document ingestion API."""

    document_id: str
    num_chunks: int
    status: str = "ingested"
    message: str = "Document successfully processed and chunked."


# ---------------------------------------------------------------------------
# Embedding Schemas
# ---------------------------------------------------------------------------
class EmbedRequest(BaseModel):
    """Request schema for embedding API."""

    texts: list[str] = Field(..., min_length=1, description="Texts to embed.")
    provider: str | None = Field(default=None, description="gemini, sentence-transformers, or default.")


class EmbedResponse(BaseModel):
    """Response schema for embedding API."""

    embeddings: list[list[float]]
    dimensions: int
    provider_used: str


# ---------------------------------------------------------------------------
# Retrieval Schemas
# ---------------------------------------------------------------------------
class RetrieveRequest(BaseModel):
    """Request schema for semantic retrieval API."""

    query: str = Field(..., min_length=2, description="User search query.")
    top_k: int = Field(default=5, ge=1, le=50, description="Top K results to retrieve.")
    session_id: str | None = Field(default=None, description="Filter by session_id.")
    filter_metadata: dict[str, Any] | None = Field(default=None, description="Metadata filters.")


class Citation(BaseModel):
    """A source citation for a research finding or retrieval chunk."""

    title: str
    url: str
    source_domain: str
    accessed_at: datetime = Field(default_factory=datetime.utcnow)
    excerpt: str | None = None
    page_number: int | None = None
    confidence_score: float = Field(default=0.85, ge=0.0, le=1.0)


class RetrievedChunk(BaseModel):
    """A single retrieved chunk with score and citation."""

    chunk: Chunk
    similarity_score: float = Field(ge=0.0, le=1.0)
    source: str
    citation: Citation


class RetrievalResponse(BaseModel):
    """Response schema for semantic retrieval API."""

    query: str
    results: list[RetrievedChunk] = Field(default_factory=list)
    total_retrieved: int = 0


# ---------------------------------------------------------------------------
# Source Verification Schemas
# ---------------------------------------------------------------------------
class SourceVerificationRequest(BaseModel):
    """Request to verify source reliability."""

    url: str
    domain: str | None = None
    content_sample: str | None = None
    published_date: str | None = None


class SourceVerificationResponse(BaseModel):
    """Response schema for source verification."""

    url: str
    domain: str
    authority_score: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)
    recency_score: float = Field(ge=0.0, le=1.0)
    domain_reputation: float = Field(ge=0.0, le=1.0)
    evidence_quality: float = Field(ge=0.0, le=1.0)
    overall_confidence_score: float = Field(ge=0.0, le=1.0)
    rationale: str


# ---------------------------------------------------------------------------
# Contradiction Detection Schemas
# ---------------------------------------------------------------------------
class ContradictionRequest(BaseModel):
    """Request to detect contradictions across evidence chunks."""

    topic: str
    evidence_texts: list[str] = Field(..., min_length=2, description="Evidence text samples to compare.")


class ContradictionClaim(BaseModel):
    """A detected contradiction claim pair."""

    claim_a: str
    claim_b: str
    supporting_sources_a: list[str] = Field(default_factory=list)
    supporting_sources_b: list[str] = Field(default_factory=list)
    confidence_level: float = Field(ge=0.0, le=1.0)
    explanation: str


class ContradictionResponse(BaseModel):
    """Response schema for contradiction detection."""

    topic: str
    contradictions_found: bool
    claims: list[ContradictionClaim] = Field(default_factory=list)
    summary: str


# ---------------------------------------------------------------------------
# Research Finding & Final Result Models
# ---------------------------------------------------------------------------
class ResearchFinding(BaseModel):
    """A single research finding from one iteration."""

    finding_id: str
    session_id: str
    iteration: int
    content: str
    citations: list[Citation] = Field(default_factory=list)
    tool_used: str
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ResearchResult(BaseModel):
    """Final result of a completed research session."""

    session_id: str
    question: str
    status: SessionStatus
    findings: list[ResearchFinding]
    total_iterations: int
    overall_confidence: float = Field(ge=0.0, le=100.0)
    report_id: str | None = None
    completed_at: datetime | None = None


class ResearchHistoryItem(BaseModel):
    """A single research session entry in the history list."""

    session_id: str
    question: str
    date: str
    status: SessionStatus
    iterations: int
    sources_count: int
    overall_confidence: float
    tags: list[str] = Field(default_factory=list)

