"""
Interface: ISandbox

Defines the contract for the Docker Sandbox Executor.

The Sandbox provides a safe, isolated environment for executing code
generated by the research agent (e.g., running experiments, data analysis,
validating hypotheses). Every execution is strictly time-limited and
resource-constrained.

Safety guarantees:
    - No network access from inside the sandbox
    - No filesystem persistence beyond the session
    - Memory and CPU hard limits enforced via Docker
    - All code is validated by Governance before execution

Implementing this module:
    - File: backend/app/sandbox/sandbox.py
    - Use Docker SDK: import docker
    - Register in backend/app/core/dependencies.py
"""

from abc import ABC, abstractmethod
from typing import Any


class ISandbox(ABC):
    """Abstract interface for the Docker-based code execution sandbox."""

    @abstractmethod
    async def execute_code(
        self,
        code: str,
        language: str = "python",
        timeout_seconds: int | None = None,
        environment_vars: dict[str, str] | None = None,
        packages: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Execute code in an isolated Docker container.

        Args:
            code: The source code to execute.
            language: Programming language ("python", "bash").
            timeout_seconds: Max execution time (overrides default setting).
            environment_vars: Environment variables to inject.
            packages: Additional packages to install before execution.

        Returns:
            Dict containing:
                - stdout: Captured standard output
                - stderr: Captured standard error
                - exit_code: Container exit code (0 = success)
                - execution_time_ms: Actual execution time
                - container_id: ID of the container used

        Raises:
            SandboxTimeoutException: If execution exceeds timeout.
            SandboxException: For other container errors.
        """
        ...

    @abstractmethod
    async def validate_code(self, code: str, language: str = "python") -> bool:
        """
        Perform static analysis to detect dangerous code patterns before execution.

        Checks for:
        - File system access outside allowed paths
        - Network calls (all network is disabled, but warn early)
        - Infinite loops (basic heuristic)
        - Excessive resource usage

        Args:
            code: The code to analyze.
            language: Programming language.

        Returns:
            True if code is safe to execute.

        Raises:
            GovernanceViolationException: If dangerous patterns are found.
        """
        ...

    @abstractmethod
    async def cleanup(self, container_id: str) -> None:
        """
        Remove a Docker container after execution.

        Args:
            container_id: The container to remove.
        """
        ...
